# -*- coding: utf-8 -*-
"""c022.10783 - Odd Sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4I8aKW2haiHNnAlfEr0Str7YusJ5aw5
"""

while True:
    try:
        n = int(input())

        for case in range(1, n+1):
            total = 0
            a = int(input())
            b = int(input())
            for i in range(a, b+1):
                if (i % 2) != 0:
                    total = total + i
            print(f"Case {case}: {total}")
    except EOFError:
        break