# -*- coding: utf-8 -*-
"""d442.10591 - Happy Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAXPLL3J2EfDLOjHjhuaVm99mcwDa58r
"""

def sumof_squared(n):
    total = 0
    while n > 0:
        digit = n % 10
        total += digit * digit
        n = n // 10
    return total

def is_happy(n):
    visited = set()
    while (n != 1 and n not in visited):
        visited.add(n)
        n = sumof_squared(n)
    return n == 1

t = int(input())
for case_num in range(1, t+1):
    n = int(input())
    if is_happy(n):
        print(f"Case #{case_num}: {n} is a Happy number.")
    else:
        print(f"Case #{case_num}: {n} is an Unhappy number.")