# -*- coding: utf-8 -*-
"""c007.00272 - TeX Quotes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNQzL04Q-rWqgWvTd8jI275gtTlUbnLt
"""

first = True
while True:
    try:
        line = input()
        for char in line:
            if char == '"':
                if first:
                    print("``", end="")
                    first = False
                else:
                    print("''", end="")
                    first = True
            else:
                print(char, end="")

        print()
    except EOFError:
        break